default:
  image: registry.gitlab.com/pages/hugo/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Remianing items should be defined in project variables
  #AWS_ACCESS_KEY_ID:
  #AWS_SECRET_ACCESS_KEY:
  #S3_ENDPOINT:
  #S3_BUCKET:


stages:
  - test
  - render
  - sync

test:
  stage: test
  script:
  - hugo
  except:
  - main

render:
  stage: render
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - main

sync:
  stage: sync
  image: amazon/aws-cli:latest
  script:
    - aws s3 sync public s3://${S3_BUCKET} --no-paginate --output=json --endpoint=https://${S3_ENDPOINT}
  needs:
    - job: render
      artifacts: true

