default:
  image: registry.gitlab.com/pages/hugo/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # Don't add a leading / here unless you want a key named "/" with
  # a subkey named "/public"...
  SUBFOLDER: public

  # Remianing items should be defined in project variables
  AWS_ACCESS_KEY_ID: setme
  AWS_SECRET_ACCESS_KEY: setme
  S3_ENDPOINT: setme
  S3_BUCKET: setme


stages:
  - test
  - render
  - sync

hugo_test:
  stage: test
  script:
  - hugo
  except:
  - main

# browser_test:
#   stage: test
#   image: buildkite/puppeteer
#   before_script:
#     # Start local hugo instance
#     FIGURE OUT THIS PART - CAN BEFORE USE ANOTHER IMAGE?   HOW WILL THEY TALK?
#     - hugo server
#   script:

render:
  stage: render
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - main

sync:
  stage: sync
  image: amazon/aws-cli:2.1.39
  script:
    # Default for resources
    - aws s3 sync public s3://$S3_BUCKET/$SUBFOLDER --no-paginate --output=json --endpoint=https://$S3_ENDPOINT --delete --exclude="*.html" --acl=public-read --cache-control "max-age=86400,public"
    # Content subject to faster change
    - aws s3 sync public s3://$S3_BUCKET/$SUBFOLDER --no-paginate --output=json --endpoint=https://$S3_ENDPOINT --exclude="*" --include="*.html" --acl=public-read --cache-control "max-age=60,public"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  needs:
    - job: render
      artifacts: true
  only:
  - main

