---
# Configured in YAML cause someday soon I will only know how to write YAML...
defaultContentLanguage: "en"
languageCode: "en-us"
title: "Voltage Noir"
copyright: '<a href="http://www.apache.org/licenses/LICENSE-2.0.txt" target="_blank" rel="noopener">© 2021 Paul Hirsch</a>'
baseurl: "/"

# 10% Inspiration / 90% choosing a theme.
theme: beautifulhugo

paginate: 100

# Self-own mode: On
enableEmoji: false

# git is not included in our build image so turning this off
#enableGitInfo: true
enableRobotsTXT: true
enableRSS: false

author: "Paul Doom"

permalinks:
  posts: /:year/:month/:title/

sitemap:
  changefreq            : "daily"
  priority              : 1
  filename              : "sitemap.xml"

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

languages:
  en:
    languageName: "English"
    title: "VoltageNoir"
    subtitle: ""
    keywords: ""

    menu:
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts"
        - identifier: "about"
          name: "About"
          url: "/about"
